---
title: "clean_data"
author: "Steven Liu"
date: "TO414 HW 4"
output: 
  html_document:
    theme: cerulean
    toc: yes
    toc_float:
      collapsed: true
---


<div style="padding: 15px; background-color: #f9f9f9; border-left: 5px solid #ccc;">
[Back to MainReportHW4.html](MainReportHW4.html#cleandata)
</div>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# clean data

```{r}
hoteldata_raw <- read.csv("hotel_booking.csv", stringsAsFactors = TRUE)

hoteldata <- hoteldata_raw[sample(1:nrow(hoteldata_raw), 0.4*nrow(hoteldata_raw)), ]


nrow(hoteldata)

anyNA(hoteldata)


hoteldata$name <- NULL
hoteldata$email <- NULL
hoteldata$credit_card <- NULL
hoteldata$phone.number <- NULL
hoteldata$agent <- NULL
hoteldata$market_segment <- NULL
hoteldata$company <- NULL
hoteldata$reservation_status <- NULL
hoteldata$reservation_status_date <- NULL


median_children <- median(hoteldata$children, na.rm = TRUE)
hoteldata$children[is.na(hoteldata$children)] <- median_children


# Assuming your factor column is df$country
tab <- sort(table(hoteldata$country), decreasing=TRUE)
cumprop <- cumsum(tab / sum(tab))
k <- min(which(cumprop >= 0.8))  # k=6 for your data (84.4%)

# Recode: top k levels stay, rest → "Other"
top_levels <- names(tab)[1:k]
hoteldata$country <- factor(ifelse(hoteldata$country %in% top_levels, 
                                      as.character(hoteldata$country), "Other"),
                               levels=c(top_levels, "Other"))

str(hoteldata)
summary(hoteldata)

```

# check NA

```{r}
anyNA(hoteldata)
which(is.na(hoteldata))

saveRDS(hoteldata, file = "hoteldata_og.rds")

summary(hoteldata)
```


<div style="padding: 15px; background-color: #f9f9f9; border-left: 5px solid #ccc;">
[Back to MainReportHW4.html](MainReportHW4.html#cleandata)
</div>
