---
title: "dummycoding"
author: "Steven Liu"
date: "TO414 HW 4"
output: 
  html_document:
    theme: cerulean
    toc: yes
    toc_float:
      collapsed: true
---

<div style="padding: 15px; background-color: #f9f9f9; border-left: 5px solid #ccc;">
[Back to MainReportHW4.html](MainReportHW4.html#cleandata)
</div>

```{r}
hoteldata <- readRDS("hoteldata_og.rds")
```

```{r}

hotel_d <- as.data.frame(model.matrix(~ . -1, data = hoteldata))

anyNA(hotel_d)
str(hotel_d)

library(janitor)

hotel_d <- clean_names(hotel_d)

saveRDS(hotel_d, file = "dummy_no_normalization.rds")

```

# unused normalization

minmax <- function(x){
  (x - min(x)) / (max(x) - min(x))
}

hotel_n_na <- as.data.frame(lapply(hotel_d, minmax))

str(hotel_n_na)

hotel_n <- na.omit(hotel_n_na)

anyNA(hotel_n)
str(hotel_n)



saveRDS(hotel_n, file = "hotel_dummy.rds")

str(hotel_n)

anyNA(hotel_n)

<div style="padding: 15px; background-color: #f9f9f9; border-left: 5px solid #ccc;">
[Back to MainReportHW4.html](MainReportHW4.html#cleandata)
</div>

