---
title: "logistic"
author: "Steven Liu"
date: "TO414 HW 4"
output: 
  html_document:
    theme: cerulean
    toc: yes
    toc_float:
      collapsed: true
---

<div style="padding: 15px; background-color: #f9f9f9; border-left: 5px solid #ccc;">
[Back to MainReportHW4.html](MainReportHW4.html#overviewofmodels)
</div>


# import data 

```{r}
train <- readRDS("train_og.rds")
test <- readRDS("test_og.rds")

str(train$assigned_room_type)
str(test)
```

# building model

```{r, warning=FALSE, cache=TRUE}
linear_model = glm(is_canceled ~ ., data = train, family = binomial)
stepmodel = step(linear_model, direction = "both", trace = 0)

stepmodel

saveRDS(stepmodel, file = "logistic.rds")
```
```{r}
pred_class <- predict(stepmodel, test, type = "response")

pred_class

saveRDS(pred_class, file = "logistic_pred.rds")

pred_factor <- ifelse(pred_class > 0.1, "1", "0")

pred_factor

library(caret)

confusionMatrix(as.factor(pred_factor), as.factor(test$is_canceled), positive = "1")
```

<div style="padding: 15px; background-color: #f9f9f9; border-left: 5px solid #ccc;">
[Back to MainReportHW4.html](MainReportHW4.html#overviewofmodels)
</div>
